#!/bin/bash

PLAYLIST=${1}
PHONE_GUESS="/run/user/${UID}/gvfs/mtp*/Card/Music"

MPD_CONFIG="${HOME}/.mpd/mpd.conf"
# by default we look for a personal mpd.conf
if [ ! -f "${MPD_CONFIG}" ]; then
  echo "no mpd.conf file found"
  exit 1
fi

# now we get the music and playlist directories
MUSIC_DIR=$(egrep '^[[:space:]]*music_directory' "${MPD_CONFIG}" | cut -f2 -d'"')
PLAYLIST_DIR=$(egrep '^[[:space:]]*playlist_directory' "${MPD_CONFIG}" | cut -f2 -d'"')

echo "${MUSIC_DIR} :: ${PLAYLIST_DIR}"

# if we weren't provided a playlist we let the user know
# what's available
if [ -z "${PLAYLIST}" ]; then
  echo "You must provide us a playlist name. Here are the ones available:"
  ls "${PLAYLIST_DIR}" | sed 's/.m3u$//; s/^/* /'
 exit 1
fi
# if we weren't provided a playlist we let the user know
# what's available
if [ ! -f "${PLAYLIST_DIR}/${PLAYLIST}.m3u" ]; then
  echo "Sorry, I could find a M3U playlist with the name \"${PLAYLIST}\" (${PLAYLIST}.m3u)"
  exit 1
fi

# now we go looking for a phone under a gvfs mount point
# they should be under /var/run/${UID}/mtp*
# since we are looking to the sync to the Card we add
# that as well
PHONE_COUNT=$(ls -d ${PHONE_GUESS} | wc -l)
if [[ ${PHONE_COUNT} -ne 1 ]]; then
  echo "Seems that there are ${PHONE_COUNT} targets to copy to"
  exit 1
fi
PHONE_MOUNT="$(readlink -f ${PHONE_GUESS})"

echo "${PHONE_MOUNT}"
gvfs-copy "${PLAYLIST_DIR}/${PLAYLIST}.m3u" "${PHONE_MOUNT}/Playlists/"
